# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import servicecmd_pb2 as servicecmd__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servicecmd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtenServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExeService = channel.unary_unary(
                '/AtenServices.AtenServices/ExeService',
                request_serializer=servicecmd__pb2.Cmd.SerializeToString,
                response_deserializer=servicecmd__pb2.CmdResponse.FromString,
                _registered_method=True)


class AtenServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExeService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtenServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExeService': grpc.unary_unary_rpc_method_handler(
                    servicer.ExeService,
                    request_deserializer=servicecmd__pb2.Cmd.FromString,
                    response_serializer=servicecmd__pb2.CmdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AtenServices.AtenServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AtenServices.AtenServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AtenServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AtenServices.AtenServices/ExeService',
            servicecmd__pb2.Cmd.SerializeToString,
            servicecmd__pb2.CmdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
