name: build-atena-alpha

on:
  push:
    branches: [alpha]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: build
        run: |
          cd AtenaAI
          dotnet build 
